apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki

datasources:
  - name: Prometheus
    uid: prometheus_uid
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      timeInterval: 15s

  - name: Loki
    uid: loki_uid
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      maxLines: 1000
