// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@company.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/employees": {
            "get": {
                "description": "Retrieves all employees",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employees"
                ],
                "summary": "Get all employees",
                "responses": {
                    "200": {
                        "description": "List of employees",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/employee-management_internal_models.Employee"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new employee in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employees"
                ],
                "summary": "Create a new employee",
                "parameters": [
                    {
                        "description": "Employee data",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_models.Employee"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Employee created successfully",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_models.Employee"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON format or validation failed",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email or employee number already exists",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/employees/{id}": {
            "get": {
                "description": "Retrieves an employee by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employees"
                ],
                "summary": "Get employee by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Employee found",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_models.Employee"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Employee not found",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing employee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employees"
                ],
                "summary": "Update employee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated employee data",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_models.Employee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Employee updated successfully",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_models.Employee"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON format or validation failed",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Employee not found",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email or employee number already exists",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an employee by ID",
                "tags": [
                    "Employees"
                ],
                "summary": "Delete employee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Employee deleted successfully (no content)"
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Employee not found",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/employee-management_internal_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "employee-management_internal_api.ErrorDetail": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "rejectedValue": {
                    "type": "string"
                }
            }
        },
        "employee-management_internal_api.ErrorResponse": {
            "description": "Standard error response structure",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/employee-management_internal_api.ErrorDetail"
                    }
                },
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "employee-management_internal_models.Employee": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "employeeNumber": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "hireDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/employee-management_internal_models.EmployeeStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "employee-management_internal_models.EmployeeStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "ON_VACATION",
                "RETIRED"
            ],
            "x-enum-varnames": [
                "StatusActive",
                "StatusOnVacation",
                "StatusRetired"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Employee Management API",
	Description:      "API for managing employees",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
