pipeline {
    agent any

    environment {
        SERVICE_DIR = 'microservices/notification-service'
        DOCKER_NET  = 'microservices-fp_microservices-network'
    }

    stages {

        stage('Build & Test') {
            agent {
                docker {
                    image 'maven:3.9-eclipse-temurin-17'
                    args "-v maven_cache:/root/.m2 --network ${DOCKER_NET}"
                    reuseNode true
                }
            }
            steps {
                dir("${SERVICE_DIR}") {
                    sh 'mvn -B clean verify'
                }
            }
        }

        stage('SonarQube Analysis') {
            agent {
                docker {
                    image 'maven:3.9-eclipse-temurin-17'
                    args "-v maven_cache:/root/.m2 --network ${DOCKER_NET}"
                    reuseNode true
                }
            }
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    withSonarQubeEnv('SonarQube') {
                        dir("${SERVICE_DIR}") {
                            sh '''
                            mvn sonar:sonar \
                                -Dsonar.projectKey=notification-service \
                                -Dsonar.login=$SONAR_TOKEN
                            '''
                        }
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        always {
            junit testResults: "${SERVICE_DIR}/target/surefire-reports/*.xml", allowEmptyResults: true
            archiveArtifacts artifacts: "${SERVICE_DIR}/target/*.jar", allowEmptyArchive: true
        }
        failure {
            echo "Pipeline failed. Revisa logs (especialmente SonarQube)."
        }
        success {
            echo "Pipeline exitoso con Quality Gate aprobado."
        }
    }
}
