jenkins:
  systemMessage: "Jenkins configured automatically via JCasC"

unclassified:
  sonarGlobalConfiguration:
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        triggers:
          skipScmCause: false
          skipUpstreamCause: false

jobs:
  - script: >
      pipelineJob('notification-service-pipeline') {
        description('Build/Test pipeline for microservices/notification-service')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/Josedzzz/microservices-fp.git')
                }
                branch('main')
              }
            }
            scriptPath('microservices/notification-service/Jenkinsfile')
            lightweight(true)
          }
        }
      }
