apiVersion: 1
contactPoints:
  - name: Discord Alerts
    receivers:
      - uid: discord_alerts_01
        type: discord
        settings:
          url: '__DISCORD_WEBHOOK_URL__'
          title: '{{ .GroupLabels.alertname }}'
          message: |
            **Severity:** {{ .GroupLabels.severity | toUpper }}
            **Service:** {{ .GroupLabels.job }}

            {{ range .Alerts.Firing -}}
            **Alert:** {{ .Labels.alertname }}
            **Instance:** {{ .Labels.instance }}
            **Value:** {{ .Value }}
            **Summary:** {{ .Annotations.summary }}
            {{ end }}
        disableResolveMessage: false

policies:
  - receiver: Discord Alerts
    group_by:
      - alertname
      - job
      - severity
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 24h
