sonar.projectKey=auth-service
sonar.projectName=Auth Service
sonar.projectVersion=1.0.0

sonar.sources=cmd,internal
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/docs/**,**/vendor/**,**/*.md

sonar.go.coverage.reportPaths=coverage.out
